name: coverage ci

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Generate coverage report
        run: ./gradlew koverXmlReport

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./build/reports/kover/report.xml