name: test ci

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Assemble
        run: ./gradlew assemble

      - name: Tests
        run: ./gradlew test

      - name: Publish
        run: ./gradlew publishToMavenLocal